version: '3.5'

services:
  postgres:
    container_name: postgres_container
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ../.env
    restart: always
    volumes:
       - ./postgres:/data/postgres
       # copy the sql script to create tables
       - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "8001:5432"
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - ../.env
    ports:
      - "8080:80"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
